from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator


DifficultyLevel = Literal["Beginner", "Intermediate", "Advanced"]
OutputLanguage = Literal["Vietnamese", "English"]
AnswerOption = Literal["A", "B", "C", "D"]


class GenerationRequest(BaseModel):
    """
    User input settings for content generation.
    """
    topic: str = Field(..., min_length=2)
    level: DifficultyLevel
    language: OutputLanguage
    question_count: int = Field(..., ge=3, le=20)
    output_types: List[str]
    learning_objective: Optional[str] = ""
    include_self_review: bool = True

    @field_validator("topic")
    @classmethod
    def topic_must_not_be_empty(cls, value: str) -> str:
        value = value.strip()

        if not value:
            raise ValueError("Topic must not be empty.")

        return value

    @field_validator("output_types")
    @classmethod
    def output_types_must_not_be_empty(cls, value: List[str]) -> List[str]:
        if not value:
            raise ValueError("At least one output type must be selected.")

        return value


class Flashcard(BaseModel):
    """
    A flashcard for quick review.
    """
    term: str = Field(..., min_length=1)
    definition: str = Field(..., min_length=1)


class QuizQuestion(BaseModel):
    """
    A multiple-choice question.
    """
    question: str = Field(..., min_length=1)
    options: Dict[AnswerOption, str]
    answer: AnswerOption
    explanation: str = Field(..., min_length=1)

    @field_validator("options")
    @classmethod
    def options_must_have_four_choices(
        cls,
        value: Dict[AnswerOption, str]
    ) -> Dict[AnswerOption, str]:
        required_options = {"A", "B", "C", "D"}

        if set(value.keys()) != required_options:
            raise ValueError("Options must include exactly A, B, C, and D.")

        for option_key, option_text in value.items():
            if not option_text.strip():
                raise ValueError(f"Option {option_key} must not be empty.")

        return value


class CodeExercise(BaseModel):
    """
    A small Python coding exercise.
    """
    title: str = Field(..., min_length=1)
    description: str = Field(..., min_length=1)
    starter_code: str = Field(..., min_length=1)
    expected_output: Optional[str] = ""
    solution: Optional[str] = ""
    explanation: Optional[str] = ""


class SelfReview(BaseModel):
    """
    AI self-review result for generated content.
    """
    quality_score: int = Field(..., ge=1, le=10)
    strengths: List[str]
    weaknesses: List[str]
    improvement_suggestions: List[str]


class LearningContent(BaseModel):
    """
    Final structured output generated by AI.
    """
    lesson_title: str = Field(..., min_length=1)
    lesson: str = Field(..., min_length=1)
    summary: str = Field(..., min_length=1)
    key_points: List[str]
    flashcards: List[Flashcard]
    quiz: List[QuizQuestion]
    code_exercise: Optional[CodeExercise] = None
    self_review: Optional[SelfReview] = None

    @field_validator("key_points")
    @classmethod
    def key_points_must_not_be_empty(cls, value: List[str]) -> List[str]:
        if not value:
            raise ValueError("Key points must not be empty.")

        return value

    @field_validator("flashcards")
    @classmethod
    def flashcards_must_not_be_empty(cls, value: List[Flashcard]) -> List[Flashcard]:
        if not value:
            raise ValueError("Flashcards must not be empty.")

        return value

    @field_validator("quiz")
    @classmethod
    def quiz_must_not_be_empty(cls, value: List[QuizQuestion]) -> List[QuizQuestion]:
        if not value:
            raise ValueError("Quiz must not be empty.")

        return value